### ISSUE TITLE
UnsatisfiedLinkError: crypto_pwhash_scryptsalsa208sha256_ll

### ISSUE THREAD

**Issue by barnabycolby** [ArteMisc/libstodium#3]
Hi,

When trying to use the crypto_pwhash_scryptsalsa208sha256_ll function in my android code, it's throwing the following exception:
`java.lang.UnsatisfiedLinkError: No implementation found for int org.abstractj.kalium.SodiumJNI.crypto_pwhash_scryptsalsa208sha256_ll(byte[], int, byte[], int, int, int, int, byte[], int) (tried Java_org_abstractj_kalium_SodiumJNI_crypto_1pwhash_1scryptsalsa208sha256_1ll and Java_org_abstractj_kalium_SodiumJNI_crypto_1pwhash_1scryptsalsa208sha256_1ll___3BI_3BIIII_3BI)
at org.abstractj.kalium.SodiumJNI.crypto_pwhash_scryptsalsa208sha256_ll(Native Method)
at org.abstractj.kalium.Sodium.crypto_pwhash_scryptsalsa208sha256_ll(Sodium.java:801)`

Any ideas?

**Comment by barnabycolby** [comment]
Solved it, had forgotten to call Stodium.StodiumInit()....
